# Change baseurl before deploy
baseURL = "https://blog.noahanna.online/"
title = "男娘教主"
theme = "hugo-theme-stack"
locale = "zh-cn"
defaultContentLanguage = "zh"
hasCJKLanguage = true
paginate = 10

[outputs]
    home = ["HTML", "RSS", "JSON"]
